"""renombre

Revision ID: 688ea36dce96
Revises: 12e47c01ac5a
Create Date: 2026-08-31 20:32:20.443608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688ea36dce96'
down_revision = '12e47c01ac5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('nombre_completo', sa.String(length=80), nullable=False))
    op.drop_column('producto', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('nombre', sa.VARCHAR(length=80), nullable=False))
    op.drop_column('producto', 'nombre_completo')
    # ### end Alembic commands ###
